"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { motion, AnimatePresence } from "framer-motion";
import { AlertTriangle, FileText, Send, Siren, Sparkles, Zap } from "lucide-react";
import { PostmortemDialog } from "@/components/warroom/postmortem-dialog";
import { planInvestigation } from "@/lib/coral/investigation";
import { PageShell } from "@/components/layout/page-shell";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Separator } from "@/components/ui/separator";
import { SeverityBadge } from "@/components/widgets/severity-badge";
import { SourceIcon } from "@/components/widgets/source-icon";
import { fixtures } from "@/lib/mock/dataset";
import { formatRelative, cn } from "@/lib/utils";
import type { Incident } from "@/lib/types";

export default function IncidentsPage() {
  const [selectedId, setSelectedId] = useState<string>(fixtures.incidents[0].id);
  const [query, setQuery] = useState("");
  const [analysis, setAnalysis] = useState<string | null>(null);
  const [analyzing, setAnalyzing] = useState(false);
  const [postmortemOpen, setPostmortemOpen] = useState(false);

  const selected = useMemo(
    () => fixtures.incidents.find((i) => i.id === selectedId)!,
    [selectedId]
  );

  const runAnalysis = async () => {
    setAnalyzing(true);
    setAnalysis(null);
    await new Promise((r) => setTimeout(r, 1400));
    setAnalysis(
      `**AI Root Cause Analysis** — generated by Coral orchestrator with [github], [sentry], [datadog], [slack] agents.\n\n` +
      `**Hypothesis (confidence 0.91):** Deploy d_7741 (v2.41.0) introduced a missing request timeout in the new gRPC PaymentsClient. Under steady traffic, slow downstream responses caused connection-pool exhaustion in payments-svc, manifesting as 502s on /checkout.\n\n` +
      `**Evidence chain:**\n` +
      `• [github] PR #3318 modified PaymentsClient gRPC stub, removed default deadline (line 84).\n` +
      `• [sentry] +14,221 TimeoutError events grouped under issue PAY-3344 starting T+0:04 after deploy.\n` +
      `• [datadog] payments-svc.grpc.in_flight saturated pool size (50/50) at T+0:06; p99 /checkout 320ms → 1.4s.\n` +
      `• [slack] #incidents discussion at T+0:08 — Priya proposed rollback path.\n\n` +
      `**Recommended actions:**\n` +
      `1. Merge PR #3322 (timeout fix) and canary to 5% — already in review.\n` +
      `2. Roll back v2.41.0 if error rate exceeds 6% within next 10m.\n` +
      `3. Add SLO burn alarm on checkout-api p99 > 800ms for 2m.\n` +
      `4. Post-incident: add lint rule requiring explicit deadline on all gRPC clients.`
    );
    setAnalyzing(false);
  };

  return (
    <PageShell
      title="Incident Investigator"
      subtitle="Natural-language incident analysis with root cause detection, error correlation, and AI-generated reports."
      actions={
        <>
          <Badge variant="destructive">
            <AlertTriangle className="h-3 w-3 mr-1" />
            {fixtures.incidents.filter((i) => i.status !== "resolved").length} active
          </Badge>
          <Button size="sm" variant="outline" onClick={() => setPostmortemOpen(true)}>
            <FileText className="h-3.5 w-3.5" /> Generate Postmortem
          </Button>
          <Button size="sm" asChild className="!bg-coral-500 !text-white hover:!bg-coral-600">
            <Link href="/war-room"><Siren className="h-3.5 w-3.5" /> War Room</Link>
          </Button>
        </>
      }
    >
      <div className="grid grid-cols-1 xl:grid-cols-[320px_1fr] gap-4">
        {/* Incident list */}
        <Card className="h-fit">
          <CardHeader>
            <CardTitle>Incidents</CardTitle>
            <Input placeholder="Filter incidents…" className="mt-2" />
          </CardHeader>
          <CardContent className="space-y-1.5 max-h-[70vh] overflow-y-auto">
            {fixtures.incidents.map((inc) => (
              <button
                key={inc.id}
                onClick={() => { setSelectedId(inc.id); setAnalysis(null); }}
                className={cn(
                  "w-full text-left glass rounded-lg p-3 transition border",
                  selectedId === inc.id
                    ? "border-primary/40 bg-primary/5 shadow-[0_0_15px_rgba(34,211,238,0.15)]"
                    : "border-transparent hover:bg-white/[0.05]"
                )}
              >
                <div className="flex items-center gap-2 mb-1">
                  <span className="font-mono text-[10px] text-muted-foreground">{inc.id}</span>
                  <SeverityBadge severity={inc.severity} />
                </div>
                <div className="text-sm font-medium line-clamp-2">{inc.title}</div>
                <div className="text-[10px] text-muted-foreground mt-1.5 flex items-center gap-1.5">
                  <SourceIcon source={inc.source} size={14} />
                  <span>{inc.service}</span>
                  <span>·</span>
                  <span>{formatRelative(inc.startedAt)}</span>
                </div>
              </button>
            ))}
          </CardContent>
        </Card>

        {/* Detail */}
        <div className="space-y-4">
          <IncidentHeader inc={selected} />

          {/* AI investigator */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Sparkles className="h-4 w-4 text-primary" /> AI Investigator
              </CardTitle>
              <CardDescription>Ask in plain English. Coral fans out across Sentry, Datadog, GitHub, and Slack.</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="flex gap-2">
                <Input
                  value={query}
                  onChange={(e) => setQuery(e.target.value)}
                  placeholder='e.g., "what changed right before this incident?"'
                  className="flex-1"
                />
                <Button onClick={runAnalysis} disabled={analyzing}>
                  {analyzing ? "Analyzing…" : <><Send className="h-3.5 w-3.5" /> Run</>}
                </Button>
                <Button variant="outline" onClick={runAnalysis} disabled={analyzing}>
                  <Zap className="h-3.5 w-3.5" /> Auto-RCA
                </Button>
              </div>

              <div className="flex flex-wrap gap-1.5 mt-3">
                {["What changed?", "Who is impacted?", "Generate postmortem", "Suggest mitigation", "Find similar past incidents"].map((s) => (
                  <button
                    key={s}
                    onClick={() => setQuery(s)}
                    className="text-[11px] px-2.5 py-1 rounded-full border border-white/10 bg-white/[0.03] hover:bg-white/[0.07] text-muted-foreground hover:text-foreground transition"
                  >
                    {s}
                  </button>
                ))}
              </div>

              <AnimatePresence>
                {analyzing && (
                  <motion.div
                    initial={{ opacity: 0, height: 0 }}
                    animate={{ opacity: 1, height: "auto" }}
                    exit={{ opacity: 0, height: 0 }}
                    className="mt-4 overflow-hidden"
                  >
                    <AgentTrace />
                  </motion.div>
                )}
                {analysis && !analyzing && (
                  <motion.div
                    initial={{ opacity: 0, y: 8 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="mt-4 glass rounded-lg p-4 text-sm leading-relaxed"
                  >
                    {analysis.split("\n\n").map((p, i) => (
                      <p key={i} className="mb-3 whitespace-pre-wrap last:mb-0" dangerouslySetInnerHTML={{ __html: p.replace(/\*\*(.+?)\*\*/g, '<strong class="text-foreground">$1</strong>') }} />
                    ))}
                    <Separator className="my-3" />
                    <div className="flex items-center gap-2 text-xs text-muted-foreground">
                      <FileText className="h-3.5 w-3.5" />
                      Generated in 1.4s · 4 agents · 12 tool calls · confidence 0.91
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </CardContent>
          </Card>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
            <CorrelatedSignals inc={selected} />
            <Timeline inc={selected} />
          </div>
        </div>
      </div>

      <PostmortemDialog
        open={postmortemOpen}
        onClose={() => setPostmortemOpen(false)}
        result={(() => {
          // Build a postmortem from the currently-selected incident by
          // mapping its timeline + signals into the investigation shape.
          const plan = planInvestigation(selected.title);
          return {
            query: selected.title,
            steps: [],
            rootCause: {
              summary: selected.rootCause ?? plan.rootCause.summary,
              confidence: plan.rootCause.confidence,
              primarySource: plan.rootCause.primarySource,
              primaryRef: plan.rootCause.primaryRef,
              affectedUsers: selected.affectedUsers || plan.rootCause.affectedUsers,
              severity: selected.severity,
              recommendedAction: plan.rootCause.recommendedAction,
              blastRadius: `${selected.service} · ${selected.affectedUsers.toLocaleString()} users · ${selected.errorRate}% errors`,
            },
            timeline: selected.timeline.map((t) => ({
              source: t.source,
              ts: t.ts,
              label: t.action,
              detail: t.details ?? "",
              evidence: `${t.source}://${t.actor}`,
              weight: 0.7,
            })),
          };
        })()}
      />
    </PageShell>
  );
}

function IncidentHeader({ inc }: { inc: Incident }) {
  return (
    <Card>
      <CardContent className="p-5">
        <div className="flex flex-wrap items-start gap-3 justify-between">
          <div className="min-w-0">
            <div className="flex items-center gap-2 mb-1">
              <span className="font-mono text-xs text-muted-foreground">{inc.id}</span>
              <SeverityBadge severity={inc.severity} />
              <Badge variant={inc.status === "resolved" ? "success" : inc.status === "mitigated" ? "warning" : "destructive"}>
                {inc.status}
              </Badge>
            </div>
            <div className="text-xl font-semibold">{inc.title}</div>
            <div className="text-sm text-muted-foreground mt-1">{inc.description}</div>
          </div>
          <div className="grid grid-cols-3 gap-3 text-center min-w-[300px]">
            <Stat label="Affected" value={inc.affectedUsers.toLocaleString()} />
            <Stat label="Error rate" value={`${inc.errorRate}%`} />
            <Stat label="Service" value={inc.service} small />
          </div>
        </div>
      </CardContent>
    </Card>
  );
}

function Stat({ label, value, small }: { label: string; value: string; small?: boolean }) {
  return (
    <div className="glass rounded-md py-2 px-3">
      <div className={cn("font-semibold tabular-nums truncate", small ? "text-sm" : "text-xl")}>{value}</div>
      <div className="text-[10px] uppercase tracking-wider text-muted-foreground">{label}</div>
    </div>
  );
}

function CorrelatedSignals({ inc }: { inc: Incident }) {
  return (
    <Card>
      <CardHeader>
        <CardTitle>Correlated Signals</CardTitle>
        <CardDescription>Cross-source events ranked by Coral confidence</CardDescription>
      </CardHeader>
      <CardContent className="space-y-2">
        {inc.correlatedSignals.length === 0 && (
          <div className="text-xs text-muted-foreground">No correlated signals.</div>
        )}
        {inc.correlatedSignals.map((s, i) => (
          <motion.div
            key={i}
            initial={{ opacity: 0, x: -4 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: i * 0.05 }}
            className="glass rounded-md p-3 flex items-start gap-3"
          >
            <SourceIcon source={s.source} size={24} />
            <div className="flex-1 min-w-0">
              <div className="text-xs flex items-center gap-2">
                <span className="uppercase tracking-wider text-muted-foreground">{s.type}</span>
                <span className="font-mono text-muted-foreground">{formatRelative(s.ts)}</span>
              </div>
              <div className="text-sm mt-0.5">{s.message}</div>
            </div>
            <div className="flex flex-col items-end gap-1">
              <div className="text-[10px] font-mono text-muted-foreground">conf</div>
              <div className="text-sm font-semibold text-primary">{(s.confidence * 100).toFixed(0)}%</div>
            </div>
          </motion.div>
        ))}
      </CardContent>
    </Card>
  );
}

function Timeline({ inc }: { inc: Incident }) {
  return (
    <Card>
      <CardHeader>
        <CardTitle>Timeline</CardTitle>
        <CardDescription>Unified event stream across sources</CardDescription>
      </CardHeader>
      <CardContent>
        <div className="relative pl-6">
          <div className="absolute left-2 top-1 bottom-1 w-px bg-gradient-to-b from-cyan-400/60 via-white/10 to-transparent" />
          {inc.timeline.map((t, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, x: -6 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: 0.1 + i * 0.06 }}
              className="relative pb-4 last:pb-0"
            >
              <div className="absolute -left-[18px] top-1 h-2.5 w-2.5 rounded-full bg-primary shadow-[0_0_8px_rgba(34,211,238,0.7)]" />
              <div className="flex items-center gap-2 text-xs">
                <SourceIcon source={t.source} size={16} />
                <span className="font-mono text-muted-foreground">{formatRelative(t.ts)}</span>
                <span className="text-muted-foreground">·</span>
                <span className="font-medium">{t.actor}</span>
              </div>
              <div className="text-sm mt-0.5">{t.action}</div>
              {t.details && <div className="text-xs text-muted-foreground mt-0.5">{t.details}</div>}
            </motion.div>
          ))}
        </div>
      </CardContent>
    </Card>
  );
}

function AgentTrace() {
  const steps = [
    { agent: "orchestrator", text: "Planning multi-agent investigation…" },
    { agent: "github", text: "Fetching recent deploys + diff for d_7741…" },
    { agent: "sentry", text: "Correlating issue groups by release tag…" },
    { agent: "datadog", text: "Querying APM + custom metrics for checkout-api…" },
    { agent: "slack", text: "Searching #incidents for relevant context…" },
    { agent: "report", text: "Synthesizing findings…" },
  ];
  return (
    <ScrollArea className="glass rounded-lg p-3 max-h-44">
      <div className="space-y-1.5 font-mono text-[11px]">
        {steps.map((s, i) => (
          <motion.div
            key={i}
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: i * 0.15 }}
            className="flex items-center gap-2"
          >
            <span className="text-cyan-400">[{s.agent}]</span>
            <span className="text-muted-foreground">{s.text}</span>
            <span className="ml-auto text-emerald-400">✓</span>
          </motion.div>
        ))}
      </div>
    </ScrollArea>
  );
}
