"use client";

import { motion } from "framer-motion";
import { AlertTriangle, ArrowRight, FileText, Target, Users, Zap } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { SourceIcon } from "@/components/widgets/source-icon";
import { SeverityBadge } from "@/components/widgets/severity-badge";
import type { InvestigationResult } from "@/lib/coral/investigation";
import { cn } from "@/lib/utils";

interface Props {
  result: InvestigationResult;
  onPostmortem?: () => void;
  onRollback?: () => void;
}

export function RootCauseCard({ result, onPostmortem, onRollback }: Props) {
  const { rootCause: rc } = result;
  const pct = Math.round(rc.confidence * 100);
  const tier = pct >= 85 ? "high" : pct >= 65 ? "medium" : "low";

  return (
    <motion.div
      initial={{ opacity: 0, scale: 0.98 }}
      animate={{ opacity: 1, scale: 1 }}
      transition={{ duration: 0.5 }}
    >
      <Card className="relative overflow-hidden">
        {/* Glow background */}
        <div className="absolute inset-0 bg-gradient-to-br from-coral-500/15 via-amber-500/10 to-cyan-500/10 pointer-events-none" />
        <div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-coral-400 to-transparent" />

        <CardContent className="relative p-6">
          <div className="flex items-center gap-3 mb-4">
            <div className="h-10 w-10 rounded-lg bg-coral-500/20 border border-coral-500/40 grid place-items-center">
              <Target className="h-5 w-5 text-coral-400" />
            </div>
            <div className="flex-1">
              <div className="text-[10px] uppercase tracking-[0.18em] text-coral-400 font-semibold">AI Root Cause Hypothesis</div>
              <div className="text-xs text-muted-foreground">Generated by Coral report agent · {result.steps.length} agents · {result.timeline.length} evidence points</div>
            </div>
            <SeverityBadge severity={rc.severity} />
          </div>

          {/* Main summary */}
          <div className="text-base leading-relaxed mb-5">{rc.summary}</div>

          {/* KPI grid */}
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 mb-5">
            <StatTile
              label="Confidence"
              value={`${pct}%`}
              accent={tier === "high" ? "emerald" : tier === "medium" ? "amber" : "coral"}
            >
              <div className="mt-2 h-1 rounded-full bg-white/[0.06] overflow-hidden">
                <motion.div
                  className={cn(
                    "h-full",
                    tier === "high" && "bg-emerald-400",
                    tier === "medium" && "bg-amber-400",
                    tier === "low" && "bg-coral-400"
                  )}
                  initial={{ width: 0 }}
                  animate={{ width: `${pct}%` }}
                  transition={{ duration: 1.2 }}
                />
              </div>
            </StatTile>

            <StatTile
              label="Root Cause"
              value={rc.primaryRef}
              icon={<SourceIcon source={rc.primarySource} size={16} />}
              accent="cyan"
            />

            <StatTile
              label="Affected Users"
              value={rc.affectedUsers.toLocaleString()}
              icon={<Users className="h-3.5 w-3.5" />}
              accent="violet"
            />

            <StatTile
              label="Blast Radius"
              value={rc.blastRadius}
              small
              icon={<AlertTriangle className="h-3.5 w-3.5" />}
              accent="amber"
            />
          </div>

          {/* Recommended action */}
          <div className="glass rounded-lg p-3 border-l-2 border-coral-500 mb-4">
            <div className="text-[10px] uppercase tracking-wider text-coral-400 font-semibold flex items-center gap-1.5">
              <Zap className="h-3 w-3" /> Recommended Action
            </div>
            <div className="text-sm mt-1">{rc.recommendedAction}</div>
          </div>

          {/* Action buttons */}
          <div className="flex flex-wrap gap-2">
            <Button onClick={onRollback} className="!bg-coral-500 !text-white hover:!bg-coral-600 !shadow-[0_0_20px_rgba(255,90,60,0.4)]">
              <ArrowRight className="h-3.5 w-3.5" /> Execute Recommended Action
            </Button>
            <Button variant="outline" onClick={onPostmortem}>
              <FileText className="h-3.5 w-3.5" /> Generate Postmortem
            </Button>
            <Badge variant="info" className="!normal-case ml-auto self-center">
              Coral confidence model · evidence-weighted
            </Badge>
          </div>
        </CardContent>
      </Card>
    </motion.div>
  );
}

function StatTile({
  label, value, accent, icon, small, children,
}: {
  label: string;
  value: string;
  accent: "emerald" | "amber" | "coral" | "cyan" | "violet";
  icon?: React.ReactNode;
  small?: boolean;
  children?: React.ReactNode;
}) {
  const c = {
    emerald: "text-emerald-400",
    amber: "text-amber-400",
    coral: "text-coral-400",
    cyan: "text-cyan-400",
    violet: "text-violet-400",
  }[accent];
  return (
    <div className="glass rounded-lg p-3">
      <div className="flex items-center gap-1.5 text-[10px] uppercase tracking-wider text-muted-foreground">
        {icon}
        <span>{label}</span>
      </div>
      <div className={cn("font-semibold tabular-nums mt-1", c, small ? "text-xs" : "text-xl")}>
        {value}
      </div>
      {children}
    </div>
  );
}
